name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 211125593418  
  ECR_REPOSITORY: 211125593418.dkr.ecr.us-east-1.amazonaws.com/app-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::211125593418:role/github-actions-role
        aws-region: us-east-1

    # - name: Login to AWS ECR
    #   id: login-ecr
    #   run: |
    #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get the build number
      id: build-number
      run: echo "::set-output name=build_number::$(date +%s)"

    - name: Build the Docker image
      run: |
        docker build -t $ECR_REPOSITORY_NAME:${{ steps.build-number.outputs.build_number }} .

    - name: Push the Docker image to ECR
      run: |
        docker push $ECR_REPOSITORY_NAME:${{ steps.build-number.outputs.build_number }}
